### ISSUE TITLE
Release new Version of Gem

### ISSUE THREAD

**Issue by xcskier56** [DaneLyons/knowtify-gem#4]
Please create a new tag and release so that master points to the new code.

Also, please push the new gem to rubygems.

Currently the VERSION is set to 0.0.3, this is because I wrote 2 releases in my fork. If you want to keep to semver I'd recommend changing the version to 0.0.2 and releasing that to rubygems.

**Comment by xcskier56** [comment]
Please publish this release to rubygems. Right now the only version in rubygems is 0.0.1 and does not include the new code.

**Comment by malps13** [comment]
+1 here :+1:

**Comment by Nowaker** [comment]
@DaneLyons Please.
